version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - app-network

  php:
    image: php:fpm
    ports:
      - "9000:9000"
    expose:
      - '9000'
    networks:
      - app-network
    volumes:
      - .:/var/www/html

  web:
    image: nginx:alpine
    volumes:
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - .:/var/www/html
    ports:
      - "8080:80"
    environment:
      #- NGINX_HOST=foobar.com
      - NGINX_PORT=80
    networks:
      - app-network

# Names our volume
volumes:
  my-db:

networks:
  app-network:
    driver: bridge